local map = require('core.utils').map

-- map('n', '<leader>t', ':tabnew +term<CR>', { noremap = true })
-- map('n', '<C-`>', ':terminal<CR>', { noremap = true })
map('t', '<Esc>', [[<C-\><C-n>]], { noremap = true })

map('t', '<A-h>', [[<C-\><C-N><C-w>h]], { noremap = true })
map('t', '<A-j>', [[<C-\><C-N><C-w>j]], { noremap = true })
map('t', '<A-k>', [[<C-\><C-N><C-w>k]], { noremap = true })
map('t', '<A-l>', [[<C-\><C-N><C-w>l]], { noremap = true })
map('i', '<A-h>', [[<C-\><C-N><C-w>h]], { noremap = true })
map('i', '<A-j>', [[<C-\><C-N><C-w>j]], { noremap = true })
map('i', '<A-k>', [[<C-\><C-N><C-w>k]], { noremap = true })
map('i', '<A-l>', [[<C-\><C-N><C-w>l]], { noremap = true })
map('n', '<A-h>', [[<C-w>h]], { noremap = true })
map('n', '<A-j>', [[<C-w>j]], { noremap = true })
map('n', '<A-k>', [[<C-w>k]], { noremap = true })
map('n', '<A-l>', [[<C-w>l]], { noremap = true })
-- map('n', '<leader>t', ':TermSelect<CR>', { noremap = true })
-- map('t', '<C-w>l', [[<C-\><C-n>:FloatermNext<CR>]], { noremap = true })
-- map('t', '<C-w>h', [[<C-\><C-n>:FloatermPrev<CR>]], { noremap = true })
-- map('t', '<C-w>n', [[<C-\><C-n>:FloatermNew<CR>]], { noremap = true })
-- map('t', '<C-w>c', [[<C-\><C-n>:FloatermKill<CR>]], { noremap = true })
